import type { PracticeAcronym } from "./types";

export const ACRONYMS: PracticeAcronym[] = [
  {
    id: "rag",
    acronym: "RAG",
    expansionEn: "Retrieval-Augmented Generation",
    expansionEs: "Generación aumentada por recuperación",
    definitionEn: "Generate answers grounded in retrieved documents.",
    definitionEs: "Generar respuestas ancladas a documentos recuperados.",
    meetingLineEn: "We rely on RAG so the agent does not invent inventory facts.",
    sourceSlug: "arquitectura",
    domain: "agents_rag",
  },
  {
    id: "hitl",
    acronym: "HITL",
    expansionEn: "Human-In-The-Loop",
    expansionEs: "Humano en el bucle",
    definitionEn: "Human approval before high-impact automation.",
    definitionEs: "Aprobación humana antes de automatizar acciones críticas.",
    meetingLineEn: "Publish stays HITL because margin errors are expensive.",
    sourceSlug: "proyectos",
    domain: "agents_rag",
  },
  {
    id: "spof",
    acronym: "SPOF",
    expansionEn: "Single Point Of Failure",
    expansionEs: "Punto único de fallo",
    definitionEn: "One component that can take the whole system down.",
    definitionEs: "Un componente que puede tumbar todo el sistema.",
    meetingLineEn: "The redesign removes the SPOF on the write path.",
    sourceSlug: "proyectos",
    domain: "architecture",
  },
  {
    id: "sla",
    acronym: "SLA",
    expansionEn: "Service Level Agreement",
    expansionEs: "Acuerdo de nivel de servicio",
    definitionEn: "Contracted availability/response targets.",
    definitionEs: "Objetivos contractuales de disponibilidad/respuesta.",
    meetingLineEn: "I will not invent an SLA—we define it after we know the scope.",
    domain: "general",
  },
  {
    id: "tco",
    acronym: "TCO",
    expansionEn: "Total Cost of Ownership",
    expansionEs: "Costo total de propiedad",
    definitionEn: "Full cost including ops, tokens, vendors and maintenance.",
    definitionEs: "Costo completo: ops, tokens, proveedores y mantenimiento.",
    meetingLineEn: "Look at TCO, not just the monthly model fee.",
    domain: "general",
  },
  {
    id: "roi",
    acronym: "ROI",
    expansionEn: "Return On Investment",
    expansionEs: "Retorno de inversión",
    definitionEn: "Business value relative to cost.",
    definitionEs: "Valor de negocio relativo al costo.",
    meetingLineEn: "We need one ROI metric before we expand autonomy.",
    domain: "general",
  },
  {
    id: "cicd",
    acronym: "CI/CD",
    expansionEn: "Continuous Integration / Continuous Delivery",
    expansionEs: "Integración y entrega continuas",
    definitionEn: "Automated build, test and release pipeline.",
    definitionEs: "Pipeline automatizado de build, test y release.",
    meetingLineEn: "Prompt versions ship through the same CI/CD discipline as code.",
    domain: "general",
  },
  {
    id: "api",
    acronym: "API",
    expansionEn: "Application Programming Interface",
    expansionEs: "Interfaz de programación de aplicaciones",
    definitionEn: "Contract for systems to talk to each other.",
    definitionEs: "Contrato para que sistemas hablen entre sí.",
    meetingLineEn: "The catalog API is the source of truth for publish.",
    domain: "fullstack",
  },
  {
    id: "rest",
    acronym: "REST",
    expansionEn: "Representational State Transfer",
    expansionEs: "Transferencia de estado representacional",
    definitionEn: "HTTP resource-oriented API style.",
    definitionEs: "Estilo de API orientado a recursos sobre HTTP.",
    meetingLineEn: "We expose a REST catalog for Woo integrations.",
    domain: "fullstack",
  },
  {
    id: "jwt",
    acronym: "JWT",
    expansionEn: "JSON Web Token",
    expansionEs: "Token web JSON",
    definitionEn: "Signed token used for auth between clients and APIs.",
    definitionEs: "Token firmado para autenticación cliente/API.",
    meetingLineEn: "Auth is JWT-based with short-lived access tokens.",
    sourceSlug: "proyectos",
    domain: "fullstack",
  },
  {
    id: "rds",
    acronym: "RDS",
    expansionEn: "Relational Database Service",
    expansionEs: "Servicio de base de datos relacional (AWS)",
    definitionEn: "Managed relational database on AWS.",
    definitionEs: "Base de datos relacional administrada en AWS.",
    meetingLineEn: "Production data sits on RDS with backups tested.",
    sourceSlug: "proyectos",
    domain: "cloud_infra",
  },
  {
    id: "ec2",
    acronym: "EC2",
    expansionEn: "Elastic Compute Cloud",
    expansionEs: "Cómputo elástico en la nube (AWS)",
    definitionEn: "AWS virtual servers.",
    definitionEs: "Servidores virtuales de AWS.",
    meetingLineEn: "Workers run on EC2 behind health checks.",
    sourceSlug: "proyectos",
    domain: "cloud_infra",
  },
  {
    id: "s3",
    acronym: "S3",
    expansionEn: "Simple Storage Service",
    expansionEs: "Servicio de almacenamiento simple (AWS)",
    definitionEn: "Object storage on AWS.",
    definitionEs: "Almacenamiento de objetos en AWS.",
    meetingLineEn: "Artifacts land in S3 with lifecycle rules.",
    sourceSlug: "proyectos",
    domain: "cloud_infra",
  },
  {
    id: "sns",
    acronym: "SNS",
    expansionEn: "Simple Notification Service",
    expansionEs: "Servicio de notificaciones (AWS)",
    definitionEn: "Pub/sub notifications on AWS.",
    definitionEs: "Notificaciones pub/sub en AWS.",
    meetingLineEn: "Alerts fan out via SNS.",
    sourceSlug: "proyectos",
    domain: "cloud_infra",
  },
  {
    id: "ses",
    acronym: "SES",
    expansionEn: "Simple Email Service",
    expansionEs: "Servicio de email (AWS)",
    definitionEn: "Transactional email on AWS.",
    definitionEs: "Email transaccional en AWS.",
    meetingLineEn: "Transactional mail goes through SES.",
    sourceSlug: "proyectos",
    domain: "cloud_infra",
  },
  {
    id: "llm",
    acronym: "LLM",
    expansionEn: "Large Language Model",
    expansionEs: "Modelo grande de lenguaje",
    definitionEn: "Foundation model that generates/understands text.",
    definitionEs: "Modelo base que genera/entiende texto.",
    meetingLineEn: "The LLM is the reasoning layer; RAG is the facts layer.",
    domain: "agents_rag",
  },
  {
    id: "mlops",
    acronym: "MLOps",
    expansionEn: "Machine Learning Operations",
    expansionEs: "Operaciones de machine learning",
    definitionEn: "Operate ML/LLM systems with evals, monitoring and cost control.",
    definitionEs: "Operar sistemas ML/LLM con evals, monitoreo y control de costo.",
    meetingLineEn: "MLOps here means evals + FinOps + health HUD, not notebooks.",
    domain: "agents_rag",
  },
  {
    id: "crm",
    acronym: "CRM",
    expansionEn: "Customer Relationship Management",
    expansionEs: "Gestión de relación con clientes",
    definitionEn: "System for pipeline, quotes and customer ops.",
    definitionEs: "Sistema de embudo, cotizaciones y operación comercial.",
    meetingLineEn: "Our CRM is a custom Django admin, separate from the public landing.",
    sourceSlug: "proyectos",
    domain: "products",
  },
  {
    id: "cms",
    acronym: "CMS",
    expansionEn: "Content Management System",
    expansionEs: "Sistema de gestión de contenidos",
    definitionEn: "Software to create and manage web content (e.g. WordPress).",
    definitionEs: "Software para crear y gestionar contenido web (p. ej. WordPress).",
    meetingLineEn: "We extend the CMS where the business already lives.",
    domain: "products",
  },
  {
    id: "sse",
    acronym: "SSE",
    expansionEn: "Server-Sent Events",
    expansionEs: "Eventos enviados por el servidor",
    definitionEn: "HTTP stream from server to client.",
    definitionEs: "Stream HTTP del servidor al cliente.",
    meetingLineEn: "Live timelines use SSE on the /vivo panel.",
    sourceSlug: "proyectos",
    domain: "fullstack",
  },
  {
    id: "orm",
    acronym: "ORM",
    expansionEn: "Object-Relational Mapper",
    expansionEs: "Mapeador objeto-relacional",
    definitionEn: "Maps database tables to typed objects (e.g. Prisma, SQLAlchemy).",
    definitionEs: "Mapea tablas a objetos tipados (p. ej. Prisma, SQLAlchemy).",
    meetingLineEn: "Prisma is our ORM so schema and TypeScript stay aligned.",
    domain: "fullstack",
  },
  {
    id: "psp",
    acronym: "PSP",
    expansionEn: "Payment Service Provider",
    expansionEs: "Proveedor de servicios de pago",
    definitionEn: "Third-party that processes card/wallet payments.",
    definitionEs: "Tercero que procesa pagos con tarjeta/billetera.",
    meetingLineEn: "We run dual PSP—Bold for LatAm and PayPal global.",
    sourceSlug: "proyectos",
    domain: "products",
  },
  {
    id: "hmac",
    acronym: "HMAC",
    expansionEn: "Hash-based Message Authentication Code",
    expansionEs: "Código de autenticación de mensaje basado en hash",
    definitionEn: "Signed payload integrity check used in payment webhooks.",
    definitionEs: "Verificación de integridad firmada usada en webhooks de pago.",
    meetingLineEn: "Bold checkout verifies HMAC before provisioning entitlements.",
    sourceSlug: "proyectos",
    domain: "products",
  },
  {
    id: "lms",
    acronym: "LMS",
    expansionEn: "Learning Management System",
    expansionEs: "Sistema de gestión de aprendizaje",
    definitionEn: "Platform for courses, lessons and exams.",
    definitionEs: "Plataforma de cursos, lecciones y exámenes.",
    meetingLineEn: "The Django LMS includes a RAG tutor with rate limits.",
    sourceSlug: "proyectos",
    domain: "products",
  },
  {
    id: "ha",
    acronym: "HA",
    expansionEn: "High Availability",
    expansionEs: "Alta disponibilidad",
    definitionEn: "Design so the service keeps running despite failures.",
    definitionEs: "Diseño para que el servicio siga pese a fallos.",
    meetingLineEn: "HA means redundancy and no SPOF under corporate scrutiny.",
    sourceSlug: "proyectos",
    domain: "architecture",
  },
  {
    id: "mvp",
    acronym: "MVP",
    expansionEn: "Minimum Viable Product",
    expansionEs: "Producto mínimo viable",
    definitionEn: "Smallest shippable slice that validates a success metric.",
    definitionEs: "Trozo mínimo entregable que valida una métrica de éxito.",
    meetingLineEn: "What is the MVP that must work next week?",
    domain: "general",
  },
  {
    id: "kpi",
    acronym: "KPI",
    expansionEn: "Key Performance Indicator",
    expansionEs: "Indicador clave de desempeño",
    definitionEn: "Metric used to judge success.",
    definitionEs: "Métrica para juzgar el éxito.",
    meetingLineEn: "Pick one KPI before we automate more.",
    sourceSlug: "proyectos",
    domain: "general",
  },
  {
    id: "eta",
    acronym: "ETA",
    expansionEn: "Estimated Time of Arrival",
    expansionEs: "Tiempo estimado de llegada / entrega",
    definitionEn: "When something is expected to be done.",
    definitionEs: "Cuándo se espera que algo esté listo.",
    meetingLineEn: "ETA is tomorrow EOD if the dependency lands today.",
    domain: "general",
  },
  {
    id: "eod",
    acronym: "EOD",
    expansionEn: "End Of Day",
    expansionEs: "Fin del día",
    definitionEn: "By the end of the working day.",
    definitionEs: "Para el final de la jornada.",
    meetingLineEn: "I will send the summary by EOD.",
    domain: "general",
  },
  {
    id: "pr",
    acronym: "PR",
    expansionEn: "Pull Request",
    expansionEs: "Solicitud de fusión (pull request)",
    definitionEn: "Proposed code change for review.",
    definitionEs: "Cambio de código propuesto para revisión.",
    meetingLineEn: "Please review the PR before we merge the prompt change.",
    domain: "general",
  },
  {
    id: "sdk",
    acronym: "SDK",
    expansionEn: "Software Development Kit",
    expansionEs: "Kit de desarrollo de software",
    definitionEn: "Libraries and tools to integrate a platform.",
    definitionEs: "Librerías y tools para integrar una plataforma.",
    meetingLineEn: "We wrap the provider SDK behind our own client.",
    domain: "fullstack",
  },
  {
    id: "ui",
    acronym: "UI",
    expansionEn: "User Interface",
    expansionEs: "Interfaz de usuario",
    definitionEn: "What the user sees and clicks.",
    definitionEs: "Lo que el usuario ve y pulsa.",
    meetingLineEn: "The health HUD is the UI for ops failures.",
    domain: "fullstack",
  },
  {
    id: "ux",
    acronym: "UX",
    expansionEn: "User Experience",
    expansionEs: "Experiencia de usuario",
    definitionEn: "Overall feel and usability of the product.",
    definitionEs: "Sensación y usabilidad general del producto.",
    meetingLineEn: "Guest checkout is a UX choice for conversion.",
    domain: "fullstack",
  },
  {
    id: "saas",
    acronym: "SaaS",
    expansionEn: "Software as a Service",
    expansionEs: "Software como servicio",
    definitionEn: "Software delivered as a subscription service.",
    definitionEs: "Software entregado como suscripción.",
    meetingLineEn: "MWS AI is SaaS with Growth/Enterprise plans.",
    sourceSlug: "proyectos",
    domain: "products",
  },
  {
    id: "vps",
    acronym: "VPS",
    expansionEn: "Virtual Private Server",
    expansionEs: "Servidor privado virtual",
    definitionEn: "Rented virtual machine for hosting.",
    definitionEs: "Máquina virtual alquilada para hosting.",
    meetingLineEn: "pagos_bold deploys on a Docker VPS.",
    sourceSlug: "proyectos",
    domain: "cloud_infra",
  },
  {
    id: "seo",
    acronym: "SEO",
    expansionEn: "Search Engine Optimization",
    expansionEs: "Optimización para motores de búsqueda",
    definitionEn: "Improve organic discoverability of pages.",
    definitionEs: "Mejorar el descubrimiento orgánico de páginas.",
    meetingLineEn: "The LMS funnel starts with an SEO landing.",
    sourceSlug: "proyectos",
    domain: "products",
  },
  {
    id: "b2b",
    acronym: "B2B",
    expansionEn: "Business to Business",
    expansionEs: "Empresa a empresa",
    definitionEn: "Selling to companies rather than consumers.",
    definitionEs: "Vender a empresas, no a consumidores.",
    meetingLineEn: "There is a B2B mentoring upsell on the course platform.",
    sourceSlug: "proyectos",
    domain: "products",
  },
  {
    id: "gdpr",
    acronym: "GDPR",
    expansionEn: "General Data Protection Regulation",
    expansionEs: "Reglamento general de protección de datos",
    definitionEn: "EU privacy regulation for personal data.",
    definitionEs: "Regulación europea de privacidad de datos personales.",
    meetingLineEn: "Retention and deletion rights need an explicit GDPR-aware policy.",
    domain: "general",
  },
  {
    id: "mcp",
    acronym: "MCP",
    expansionEn: "Model Context Protocol",
    expansionEs: "Protocolo de contexto del modelo",
    definitionEn: "Protocol for exposing tools/context to agents.",
    definitionEs: "Protocolo para exponer tools/contexto a agentes.",
    meetingLineEn: "Agent tools are MCP-style with least privilege.",
    sourceSlug: "proyectos",
    domain: "agents_rag",
  },
  {
    id: "yolo",
    acronym: "YOLO",
    expansionEn: "You Only Look Once",
    expansionEs: "Detección visual en una pasada (YOLO)",
    definitionEn: "Real-time object detection model family used in Nova vision stack.",
    definitionEs: "Familia de modelos de detección de objetos en tiempo real en el stack de visión de Nova.",
    meetingLineEn: "Vision health includes the YOLO subsystem in the HUD.",
    sourceSlug: "arquitectura",
    domain: "agents_rag",
  },
  {
    id: "stt",
    acronym: "STT",
    expansionEn: "Speech To Text",
    expansionEs: "Voz a texto",
    definitionEn: "Convert audio into text.",
    definitionEs: "Convertir audio en texto.",
    meetingLineEn: "STT is one of the monitored Nova subsystems.",
    sourceSlug: "arquitectura",
    domain: "agents_rag",
  },
  {
    id: "tts",
    acronym: "TTS",
    expansionEn: "Text To Speech",
    expansionEs: "Texto a voz",
    definitionEn: "Convert text into spoken audio.",
    definitionEs: "Convertir texto en audio hablado.",
    meetingLineEn: "TTS health is visible next to STT in the HUD.",
    sourceSlug: "arquitectura",
    domain: "agents_rag",
  },
  {
    id: "idempotent",
    acronym: "Idempotent webhook",
    expansionEn: "Idempotent webhook handling",
    expansionEs: "Manejo idempotente de webhooks",
    definitionEn: "Processing the same webhook twice does not double-charge or double-provision.",
    definitionEs: "Procesar el mismo webhook dos veces no cobra ni provisiona dos veces.",
    meetingLineEn: "Payment webhooks must be idempotent before we go live.",
    sourceSlug: "proyectos",
    domain: "products",
  },
];

export function getAcronym(id: string): PracticeAcronym | undefined {
  return ACRONYMS.find((a) => a.id === id);
}
