import { AUDITOR_PANELS, INTERVIEW_QUESTIONS } from "@/lib/interview-bank";
import type {
  DrillItem,
  MeetingScenario,
  PracticeDifficulty,
} from "./types";

export const MEETING_SCENARIOS: MeetingScenario[] = [
  {
    slug: "standup",
    titleEn: "Daily standup",
    titleEs: "Daily standup",
    brief: `You are a teammate in a remote standup. Speak in short turns. Ask Ricardo for yesterday/today/blockers. Push for a clear ETA when he is vague. Use natural meeting English.`,
    goal: "Ricardo gives a crisp status with blockers and ETA.",
    difficulty: "baja",
  },
  {
    slug: "sprint-planning",
    titleEn: "Sprint planning",
    titleEs: "Sprint planning",
    brief: `You are the Scrum facilitator. Discuss capacity, risks and a thin slice for the agent/RAG work. Challenge scope creep politely.`,
    goal: "Agree on a thin vertical slice and owners.",
    difficulty: "media",
  },
  {
    slug: "design-review",
    titleEn: "Design review",
    titleEs: "Design review",
    brief: `You are a staff engineer reviewing architecture. Ask about trade-offs: local-first vs cloud, HITL vs full-auto, SPOF, evals. Demand concrete answers.`,
    goal: "Ricardo states trade-offs and a rollback/observability plan.",
    difficulty: "alta",
  },
  {
    slug: "stakeholder-update",
    titleEn: "Stakeholder update",
    titleEs: "Update a stakeholder",
    brief: `You are a non-technical product owner. Ask for impact, options with costs, and next week’s MVP. Get impatient with jargon.`,
    goal: "Clear impact + two options + next step without invented dates.",
    difficulty: "media",
  },
  {
    slug: "difficult-feedback",
    titleEn: "Difficult feedback",
    titleEs: "Feedback difícil",
    brief: `You are a manager giving tough feedback: a demo impressed but token cost spiked. Ask Ricardo how he’ll respond professionally.`,
    goal: "Ricardo owns the issue, proposes measurement and a thinner pilot.",
    difficulty: "alta",
  },
  {
    slug: "client-call",
    titleEn: "Client discovery call",
    titleEs: "Llamada de discovery con cliente",
    brief: `You are a skeptical SME owner who wants AI yesterday. Ask price and timeline early. React well to honest scope questions.`,
    goal: "Ricardo redirects to MVP metric and a 15-min technical framing without inventing price.",
    difficulty: "alta",
  },
];

export function getMeetingScenario(slug: string): MeetingScenario | undefined {
  return MEETING_SCENARIOS.find((s) => s.slug === slug);
}

export function interviewPanels() {
  return AUDITOR_PANELS.map((p) => ({
    id: p.id,
    name: p.name,
    audience: p.audience,
    description: p.description,
  }));
}

export function questionsForPanel(
  panelId: string,
  locale: "en" | "es",
  difficulty?: PracticeDifficulty,
  limit = 8,
) {
  let qs = INTERVIEW_QUESTIONS.filter((q) => q.panel === panelId);
  if (difficulty) qs = qs.filter((q) => q.difficulty === difficulty);
  return qs.slice(0, limit).map((q) => ({
    id: q.id,
    text: locale === "en" ? q.en : q.es,
    mustCover: q.mustCover,
    redFlags: q.redFlags,
    difficulty: q.difficulty,
    audience: q.audience,
  }));
}

export const DRILL_BANK: DrillItem[] = [
  {
    id: "d1",
    pack: "meeting",
    promptEn: "You’re blocked on a product decision. Best standup line?",
    promptEs: "Estás bloqueado por una decisión de producto. ¿Mejor línea de standup?",
    options: [
      "Blocked on a product decision: HITL vs full-auto. I need a call on that.",
      "Everything is fine, no updates.",
      "I will maybe finish something someday.",
      "The system is broken forever.",
    ],
    correctIndex: 0,
    explanationEn: "Name the blocker and the decision you need.",
    explanationEs: "Nombra el bloqueo y la decisión que necesitas.",
    tags: ["standup", "blockers"],
  },
  {
    id: "d2",
    pack: "soften",
    promptEn: "Disagree with a stakeholder without fighting.",
    promptEs: "Discrepar con un stakeholder sin pelear.",
    options: [
      "That’s wrong and you know it.",
      "I’d push back slightly — the trade-off is speed versus margin risk.",
      "Whatever you say.",
      "I refuse to discuss this.",
    ],
    correctIndex: 1,
    explanationEn: "Soft pushback + explicit trade-off.",
    explanationEs: "Pushback suave + trade-off explícito.",
    tags: ["soften", "client"],
  },
  {
    id: "d3",
    pack: "glossary",
    promptEn: "What does RAG mean in your stack?",
    promptEs: "¿Qué significa RAG en tu stack?",
    options: [
      "A random answer generator with no sources",
      "Retrieve relevant docs, then generate grounded in that context",
      "Fine-tune only, no retrieval",
      "A database backup tool",
    ],
    correctIndex: 1,
    explanationEn: "RAG = retrieval then generation grounded in context.",
    explanationEs: "RAG = recuperar y luego generar anclado al contexto.",
    tags: ["rag", "agents_rag"],
  },
  {
    id: "d4",
    pack: "glossary",
    promptEn: "Why HITL before Woo publish?",
    promptEs: "¿Por qué HITL antes de publicar a Woo?",
    options: [
      "Because automation is always illegal",
      "To protect margin where errors are expensive",
      "Because Woo cannot be automated",
      "Only for demos",
    ],
    correctIndex: 1,
    explanationEn: "HITL protects margin on irreversible commerce actions.",
    explanationEs: "HITL protege margen en acciones irreversibles de commerce.",
    tags: ["hitl", "commerce"],
  },
  {
    id: "d5",
    pack: "interview",
    promptEn: "Best STAR opener?",
    promptEs: "¿Mejor apertura STAR?",
    options: [
      "I am a hard worker.",
      "The situation was… What I owned was…",
      "Let me list all my skills.",
      "I don’t remember.",
    ],
    correctIndex: 1,
    explanationEn: "Situation + ownership sets a senior frame.",
    explanationEs: "Situación + ownership enmarca seniority.",
    tags: ["star", "interview"],
  },
  {
    id: "d6",
    pack: "defer",
    promptEn: "Asked for a number you don’t have live.",
    promptEs: "Te piden un número que no tienes en vivo.",
    options: [
      "Invent a confident figure",
      "I don’t want to guess — I’ll confirm and follow up",
      "Change the subject to sports",
      "Say the system is perfect",
    ],
    correctIndex: 1,
    explanationEn: "Defer without inventing facts.",
    explanationEs: "Diferir sin inventar hechos.",
    tags: ["defer", "grounding"],
  },
  {
    id: "d7",
    pack: "acronym",
    promptEn: "SPOF expands to…",
    promptEs: "SPOF significa…",
    options: [
      "Single Point Of Failure",
      "Simple Protocol Of Files",
      "Secure Private Office Firewall",
      "System Performance Output Factor",
    ],
    correctIndex: 0,
    explanationEn: "SPOF = Single Point Of Failure.",
    explanationEs: "SPOF = punto único de fallo.",
    tags: ["spof", "architecture"],
  },
  {
    id: "d8",
    pack: "acronym",
    promptEn: "HITL expands to…",
    promptEs: "HITL significa…",
    options: [
      "High Intensity Training Loop",
      "Human-In-The-Loop",
      "Hybrid Internet Transfer Layer",
      "Host Internal Task List",
    ],
    correctIndex: 1,
    explanationEn: "HITL = Human-In-The-Loop.",
    explanationEs: "HITL = humano en el bucle.",
    tags: ["hitl"],
  },
  {
    id: "d9",
    pack: "design",
    promptEn: "Best line in a design review about agents?",
    promptEs: "¿Mejor línea en design review sobre agentes?",
    options: [
      "AI will magically fix everything",
      "I’d start with one agent + curated RAG and evals before splitting",
      "We need 50 agents on day one",
      "Skip measurement",
    ],
    correctIndex: 1,
    explanationEn: "Thin agent + RAG + evals before multi-agent split.",
    explanationEs: "Agente fino + RAG + evals antes de partir.",
    tags: ["design", "agents"],
  },
  {
    id: "d10",
    pack: "client",
    promptEn: "Client asks for a blind price.",
    promptEs: "El cliente pide precio a ciegas.",
    options: [
      "Quote a random monthly fee",
      "No fixed public pricing — scope first; recommend a 15-min technical call",
      "Refuse to ever talk money",
      "Send a 40-page proposal immediately",
    ],
    correctIndex: 1,
    explanationEn: "Scope before price; offer the technical call.",
    explanationEs: "Alcance antes de precio; ofrecer la llamada técnica.",
    tags: ["client", "pricing"],
  },
  {
    id: "d11",
    pack: "connectors",
    promptEn: "Best connector to concede then nuance?",
    promptEs: "¿Mejor conector para conceder y matizar?",
    options: ["Therefore", "That said", "Specifically", "For example"],
    correctIndex: 1,
    explanationEn: "“That said” softens a contrast after agreeing.",
    explanationEs: "“That said” matiza tras conceder.",
    tags: ["connectors"],
  },
  {
    id: "d12",
    pack: "false_friends",
    promptEn: "In a meeting, “actually” most naturally means…",
    promptEs: "En reunión, “actually” suele significar…",
    options: [
      "Currently / right now (igual que “actualmente”)",
      "In fact / as a correction",
      "Actively working",
      "Accidentally",
    ],
    correctIndex: 1,
    explanationEn: "False friend: actually ≠ actualmente.",
    explanationEs: "False friend: actually no es actualmente.",
    tags: ["false_friends"],
  },
  {
    id: "d13",
    pack: "meeting",
    promptEn: "Close a call professionally.",
    promptEs: "Cerrar una call con profesionalismo.",
    options: [
      "Bye",
      "Action item for me… I’ll send a summary. Next step is…",
      "We talked a lot",
      "See you never",
    ],
    correctIndex: 1,
    explanationEn: "Owners + summary + next step.",
    explanationEs: "Owners + resumen + siguiente paso.",
    tags: ["close"],
  },
  {
    id: "d14",
    pack: "glossary",
    promptEn: "Token FinOps means…",
    promptEs: "FinOps de tokens significa…",
    options: [
      "Ignoring model cost",
      "Measuring and controlling LLM spend as an operating metric",
      "Only using free models forever",
      "Deleting logs",
    ],
    correctIndex: 1,
    explanationEn: "Measure token/crew cost like any ops metric.",
    explanationEs: "Medir costo de tokens/crew como métrica ops.",
    tags: ["finops"],
  },
  {
    id: "d15",
    pack: "interview",
    promptEn: "Evidence of seniority?",
    promptEs: "¿Evidencia de seniority?",
    options: [
      "Years alone",
      "Ownership: design + operate production systems with trade-offs and observability",
      "Buzzwords",
      "Working nights",
    ],
    correctIndex: 1,
    explanationEn: "Ownership of production systems.",
    explanationEs: "Ownership de sistemas en producción.",
    tags: ["seniority"],
  },
  {
    id: "d16",
    pack: "acronym",
    promptEn: "PSP in payments means…",
    promptEs: "PSP en pagos significa…",
    options: [
      "Payment Service Provider",
      "Primary Storage Partition",
      "Public Secure Password",
      "Python Script Package",
    ],
    correctIndex: 0,
    explanationEn: "PSP = Payment Service Provider (Bold/PayPal).",
    explanationEs: "PSP = proveedor de pagos.",
    tags: ["psp", "payments"],
  },
  {
    id: "d17",
    pack: "soften",
    promptEn: "Ask for clarification politely.",
    promptEs: "Pedir aclaración con cortesía.",
    options: [
      "That makes no sense",
      "Quick clarification… / Help me understand…",
      "You are confusing",
      "Skip it",
    ],
    correctIndex: 1,
    explanationEn: "Clarification phrases keep rapport.",
    explanationEs: "Frases de aclaración mantienen el rapport.",
    tags: ["open", "soften"],
  },
  {
    id: "d18",
    pack: "design",
    promptEn: "Phased migration vs rewrite — preferred default on critical systems?",
    promptEs: "Migración por fases vs rewrite — ¿default en sistemas críticos?",
    options: [
      "Always rewrite everything",
      "Phased migration for continuity; rewrite only when risk is lower",
      "Never change anything",
      "Only change UI colors",
    ],
    correctIndex: 1,
    explanationEn: "Continuity first on critical systems.",
    explanationEs: "Continuidad primero en sistemas críticos.",
    tags: ["architecture"],
  },
  {
    id: "d19",
    pack: "client",
    promptEn: "Explain dual PSP simply.",
    promptEs: "Explicar dual PSP con simpleza.",
    options: [
      "We use two payment providers for LatAm and global coverage with idempotent webhooks",
      "We accept only cash",
      "Payments are magic",
      "One broken gateway is enough",
    ],
    correctIndex: 0,
    explanationEn: "Bold LatAm + PayPal global, idempotent webhooks.",
    explanationEs: "Bold LatAm + PayPal global, webhooks idempotentes.",
    tags: ["payments", "lms"],
  },
  {
    id: "d20",
    pack: "meeting",
    promptEn: "Someone used heavy jargon with a non-technical stakeholder.",
    promptEs: "Alguien usó mucha jerga con un stakeholder no técnico.",
    options: [
      "Add more jargon",
      "In other words… here’s the impact and two options with costs",
      "Ignore them",
      "Send a research paper",
    ],
    correctIndex: 1,
    explanationEn: "Translate to impact + options.",
    explanationEs: "Traducir a impacto + opciones.",
    tags: ["client", "connectors"],
  },
];

export function getDrill(id: string): DrillItem | undefined {
  return DRILL_BANK.find((d) => d.id === id);
}

export function nextDrill(excludeIds: string[] = []): DrillItem {
  const pool = DRILL_BANK.filter((d) => !excludeIds.includes(d.id));
  const list = pool.length ? pool : DRILL_BANK;
  return list[Math.floor(Math.random() * list.length)]!;
}
